WIP: Feat/push notifications
Voltz-Protocol/v1-subgraph pull request #36
Opened 2022-12-05 18:07 UTC by Sol3iman

- The way the rate oracle information is grabbed for handleIrsInstanceDeployed overwrites the previous instance 
- This part of the code should be refactored to load the rateOracle instance and not overwrite it with a new one which has identical entries
- These comments are just to keep track of the WIP

2022-12-08 11:03 UTC, avniculae commented on src/mappings/notifications/EPNSNotification.ts
> +  log.info('New id of EpnsNotificationCounter is: {}', [id1]);
This is not a new ID, right? EpnsNotificationCounter would always have the subgraphID ID. I think you can just remove the id1 variable, as the name is not suggestive and we can just use subgraphID

2022-12-08 11:03 UTC, avniculae commented on src/mappings/notifications/EPNSNotification.ts
> +  const id2 = `${subgraphID}+${count}`;
use a more suggestive name

2022-12-08 11:03 UTC, avniculae commented on src/mappings/notifications/EPNSNotification.ts
> +  if (epnsPushNotification == null) {
this should always be null, right? shall we return if it's not?

2022-12-08 11:14 UTC, Sol3iman commented on src/mappings/marginEngine/handleLiquidatePosition.ts
> +export const subgraphID = 'voltzprotocol/voltz-goerli'; // change to mainnet when deploying to mainnet subgraph, maybe keep this in the main mappings file?
I agree, will do this

2022-12-08 11:14 UTC, Sol3iman commented on src/mappings/factory/handleIrsInstanceDeployed.ts
> +  const recipient = '0x45556408e543158f74403e882E3C8c23eCD9f73'; // goerli test channel address
agreed

2022-12-08 11:14 UTC, Sol3iman commented on src/mappings/marginEngine/handleLiquidatePosition.ts
> +  const notification = `{
agreed

2022-12-08 13:24 UTC, 0xZenus requested changes

2022-12-08 13:24 UTC, 0xZenus commented on src/mappings/factory/handleIrsInstanceDeployed.ts
> +  const notification = `{
Either that, or I would move this to a function in the same file (i.e. pushIRSDeployedNotification). Letting this code here decreases readability and also mixtures two different things (i.e. the actual handler and the notification push).

2022-12-08 13:24 UTC, 0xZenus commented on src/mappings/marginEngine/handleLiquidatePosition.ts
> +  const notification = `{
Either that, or I would move this to a function in the same file (i.e. pushLiquidationNotification). Letting this code here decreases readability and also mixtures two different things (i.e. the actual handler and the notification push).

2022-12-12 14:21 UTC, Sol3iman commented on src/mappings/marginEngine/handleLiquidatePosition.ts
> +export const subgraphID = 'voltzprotocol/voltz-goerli'; // change to mainnet when deploying to mainnet subgraph, maybe keep this in the main mappings file?
done

2022-12-12 14:21 UTC, Sol3iman commented on src/mappings/factory/handleIrsInstanceDeployed.ts
> +  const recipient = '0x45556408e543158f74403e882E3C8c23eCD9f73'; // goerli test channel address
done

2022-12-12 14:21 UTC, Sol3iman commented on src/mappings/factory/handleIrsInstanceDeployed.ts
> +  const notification = `{
I created a helper function called sendPushNotification

2022-12-12 14:22 UTC, Sol3iman commented on src/mappings/marginEngine/handleLiquidatePosition.ts
> +  const notification = `{
I created a helper function called sendPushNotification

2022-12-12 14:22 UTC, Sol3iman commented on src/mappings/notifications/EPNSNotification.ts
> +import { BigInt, log } from '@graphprotocol/graph-ts';
moved it to /mappings/notifications

2022-12-12 14:22 UTC, Sol3iman commented on src/mappings/notifications/EPNSNotification.ts
> +  const count = epnsNotificationCounter.totalCount.toHexString();
This is all from a boilerplate template

2022-12-13 08:45 UTC, 0xZenus approved these changes

2022-12-13 08:45 UTC, 0xZenus commented on src/mappings/factory/handleIrsInstanceDeployed.ts
> +
Could you place the code below into a separate function (that stays below this handler in the file)?
So we separate the handler logic from the notification logic.

2023-05-23 12:36 UTC, closed without merging